# Setup
title:               Data Science Project on Ice Hockey
tagline:             'An insightful analysis of Ice Hockey'
description:         'Using the <a href="https://gitlab.com/dword4/nhlapi" target="_blank">NHL stats API</a>, we are able to create a detailed analysis of the <a href="https://www.nhl.com/gamecenter/tor-vs-wpg/2017/10/04/2017020001/recap/plays#game=2017020001,game_state=final,lock_state=final,game_tab=plays" target="_blank">play-by-play</a> data using machine learning methods and visualize the findings in a cohenrent manner.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  jizhou:
    name:              Ji Zhou Wang
    url:               https://github.com/jawing/
    email:             jizhou.wang@mila.quebec
  abhay:
    name:              Abhay Puri
    url:               
    email:             
  binulal:
    name:              Binulal Narayanan
    url:               
    email:             
  qilin:
    name:              Qilin Wang
    url:                   https://github.com/QilinWang
    email:               qilin@fastmail.com
# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
